name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.0'

      - name: Install Geode CLI
        run: |
          curl -LO https://github.com/geode-sdk/cli/releases/download/v3.7.4/geode-cli-v3.7.4-win.zip
          tar -xf geode-cli-v3.7.4-win.zip
          echo "${{ github.workspace }}" >> $GITHUB_PATH

      - name: Setup Geode SDK
        run: |
          ./geode.exe profile add --name BulutProfil "${{ github.workspace }}"
          ./geode.exe sdk install v3.0.0-beta.1
          echo "GEODE_SDK=C:/Users/runneradmin/AppData/Local/Geode/sdk/v3.0.0-beta.1" >> $GITHUB_ENV

      - name: Configure and Build
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A win32 -DCMAKE_BUILD_TYPE=Release -DGEODE_DONT_INCLUDE_DEFAULT_MOD_JSON=ON
          cmake --build build --config Release
