name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.0'

      - name: Build Mod with Geode SDK
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v3.0.0-beta.1
